services:
  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    ports:
      - '3000:3000'
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:3000/health']
      interval: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    depends_on:
      auth:
        condition: service_healthy
    ports:
      - '4200:80'
